"""deskflow init - guided initialization and configuration."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

console = Console()


def init_command() -> None:
    """Initialize DeskFlow configuration with guided setup."""
    console.print(
        Panel.fit(
            "[bold green]Coolaw DeskFlow[/bold green] - Initialization Wizard",
            border_style="green",
        )
    )
    console.print()

    project_root = Path.cwd()
    env_path = project_root / ".env"

    if env_path.exists():
        overwrite = Confirm.ask(
            "[yellow].env file already exists.[/yellow] Overwrite?",
            default=False,
        )
        if not overwrite:
            console.print("[dim]Keeping existing .env file.[/dim]")
            return

    # LLM Provider
    console.print("[bold]Step 1: LLM Provider[/bold]")
    provider = Prompt.ask(
        "Select provider",
        choices=["anthropic", "openai", "dashscope"],
        default="anthropic",
    )

    # API Key
    console.print(f"\n[bold]Step 2: {provider.title()} API Key[/bold]")
    api_key = Prompt.ask("Enter your API key", password=True)

    if not api_key:
        console.print("[red]API key cannot be empty.[/red]")
        raise typer.Exit(1)

    # Model
    console.print("\n[bold]Step 3: Model Selection[/bold]")
    model_defaults = {
        "anthropic": "claude-3-5-sonnet-20241022",
        "openai": "gpt-4o",
        "dashscope": "qwen-max",
    }
    model = Prompt.ask("Model name", default=model_defaults.get(provider, ""))

    # Server
    console.print("\n[bold]Step 4: Server Configuration[/bold]")
    port = Prompt.ask("API port", default="8420")

    # Build .env content
    lines = [
        "# Coolaw DeskFlow Configuration",
        "# Generated by: deskflow init",
        "",
        f"DESKFLOW_LLM_PROVIDER={provider}",
        "DESKFLOW_LLM_MAX_TOKENS=4096",
        "DESKFLOW_LLM_TEMPERATURE=0.7",
        "",
    ]

    if provider == "anthropic":
        lines.extend([
            f"DESKFLOW_ANTHROPIC_API_KEY={api_key}",
            f"DESKFLOW_ANTHROPIC_MODEL={model}",
        ])
    elif provider == "openai":
        lines.extend([
            f"DESKFLOW_OPENAI_API_KEY={api_key}",
            "DESKFLOW_OPENAI_BASE_URL=https://api.openai.com/v1",
            f"DESKFLOW_OPENAI_MODEL={model}",
        ])
    elif provider == "dashscope":
        lines.extend([
            f"DESKFLOW_DASHSCOPE_API_KEY={api_key}",
            f"DESKFLOW_DASHSCOPE_MODEL={model}",
        ])

    lines.extend([
        "",
        "DESKFLOW_HOST=127.0.0.1",
        f"DESKFLOW_PORT={port}",
        "DESKFLOW_LOG_LEVEL=INFO",
        "",
        "DESKFLOW_DB_PATH=data/db/deskflow.db",
        "DESKFLOW_MEMORY_CACHE_SIZE=1000",
        "",
        "DESKFLOW_TOOL_TIMEOUT=30",
        "DESKFLOW_TOOL_MAX_PARALLEL=3",
        "DESKFLOW_ALLOWED_PATHS=~/Projects,~/Documents",
        "",
    ])

    env_content = "\n".join(lines)
    env_path.write_text(env_content, encoding="utf-8")

    # Create data directories
    (project_root / "data" / "db").mkdir(parents=True, exist_ok=True)
    (project_root / "data" / "logs").mkdir(parents=True, exist_ok=True)
    (project_root / "data" / "cache").mkdir(parents=True, exist_ok=True)

    console.print()
    console.print(
        Panel.fit(
            "[bold green]Initialization complete![/bold green]\n\n"
            f"  Config: [dim]{env_path}[/dim]\n"
            f"  Provider: [cyan]{provider}[/cyan]\n"
            f"  Model: [cyan]{model}[/cyan]\n"
            f"  Port: [cyan]{port}[/cyan]\n\n"
            "Next steps:\n"
            "  [green]deskflow serve[/green]  - Start the API server\n"
            "  [green]deskflow chat[/green]   - Start interactive chat\n"
            "  [green]deskflow status[/green] - Check system status",
            border_style="green",
        )
    )
