"""DeskFlow errors module."""

from deskflow.errors.exceptions import (
    ConfigError,
    ConfigValidationError,
    DeskFlowError,
    DeskFlowMemoryError,
    LLMAllProvidersFailedError,
    LLMConnectionError,
    LLMContextOverflowError,
    LLMError,
    LLMRateLimitError,
    LLMResponseError,
    MemoryRetrievalError,
    MemoryStorageError,
    SkillError,
    SkillNotFoundError,
    SkillSandboxError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolSecurityError,
    ToolTimeoutError,
)

__all__ = [
    "ConfigError",
    "ConfigValidationError",
    "DeskFlowError",
    "DeskFlowMemoryError",
    "LLMAllProvidersFailedError",
    "LLMConnectionError",
    "LLMContextOverflowError",
    "LLMError",
    "LLMRateLimitError",
    "LLMResponseError",
    "MemoryRetrievalError",
    "MemoryStorageError",
    "SkillError",
    "SkillNotFoundError",
    "SkillSandboxError",
    "ToolError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ToolSecurityError",
    "ToolTimeoutError",
]
